services:
  # MongoDB Service
  mongo:
    image: mongo
    restart: always    
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console (Web UI)
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - my_network  

  # PostgreSQL Service
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

  # .NET API Service
  api:
    build:
      context: .
      dockerfile: ./Backend.Erp.Skeleton.Api/Dockerfile
    container_name: dotnet_api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "5000:80"
    depends_on:
      - mongo
      - db
      - minio
    restart: always
    networks:
      - my_network

volumes:
  postgres_data:
    driver: local    
  minio_data:

networks:
  my_network:
    driver: bridge
